# Generated by Django 5.1.2 on 2024-10-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_grade_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animematerials',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='anime.category'),
        ),
    ]
