# Generated by Django 5.1.2 on 2024-10-26 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_animematerials_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='animematerials',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animematerials',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animematerials',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
