# Generated by Django 5.1.2 on 2024-10-26 18:15

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_animematerials_date_add_animematerials_date_create_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animematerials',
            managers=[
                ('animanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
