# Generated by Django 5.1.2 on 2024-10-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_animematerials_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='animematerials',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
