# Generated by Django 5.1.2 on 2024-10-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_rename_content_animematerials_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='animematerials',
            name='en_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='animematerials',
            name='jp_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='animematerials',
            name='status',
            field=models.TextField(choices=[('Вышло', 'Is out'), ('Онгоинг', 'Ongoing')], default='Вышло'),
        ),
        migrations.AddField(
            model_name='animematerials',
            name='studia',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
