# Generated by Django 5.1.2 on 2024-10-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_animematerials_en_title_animematerials_jp_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animematerials',
            old_name='studia',
            new_name='studio',
        ),
    ]
