# Generated by Django 5.1.2 on 2024-10-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_rename_studia_animematerials_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(blank=True, default=0)),
                ('unique_views', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='animematerials',
            old_name='views',
            new_name='view',
        ),
        migrations.RemoveField(
            model_name='animematerials',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='animematerials',
            name='status',
            field=models.TextField(choices=[('Вышел', 'Is out'), ('Онгоинг', 'Ongoing')], default='Вышел'),
        ),
        migrations.AlterField(
            model_name='animematerials',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
