# Generated by Django 5.1.2 on 2024-10-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_views_rename_views_animematerials_view_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animematerials',
            name='view',
        ),
    ]
