# Generated by Django 5.1.2 on 2024-10-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_remove_animematerials_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='animematerials',
            name='view',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='views', to='anime.views'),
        ),
    ]
