# Generated by Django 5.1.2 on 2024-10-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animematerials',
            name='view',
        ),
        migrations.AddField(
            model_name='animematerials',
            name='view',
            field=models.ManyToManyField(blank=True, null=True, related_name='views', to='anime.views'),
        ),
    ]
