# Generated by Django 5.1.2 on 2024-10-28 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_remove_animematerials_view_animematerials_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animematerials',
            name='view',
        ),
        migrations.RemoveField(
            model_name='index',
            name='anime',
        ),
        migrations.AddField(
            model_name='animematerials',
            name='view',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='views', to='anime.views'),
        ),
        migrations.AddField(
            model_name='index',
            name='anime',
            field=models.ManyToManyField(blank=True, null=True, related_name='anime', to='anime.animematerials'),
        ),
    ]
