# Generated by Django 5.1.2 on 2024-10-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_remove_animematerials_view_remove_index_anime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animematerials',
            name='episode',
            field=models.IntegerField(blank=True, default=12),
        ),
    ]
