# Generated by Django 5.1.2 on 2024-10-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0019_animematerials_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='nslug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
