# Generated by Django 5.1.2 on 2024-10-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0020_index_nslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='class_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
