# Generated by Django 5.1.2 on 2024-10-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0021_index_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
