# Generated by Django 5.1.2 on 2024-11-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0022_alter_index_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='index',
            old_name='nslug',
            new_name='name_slug',
        ),
        migrations.RemoveField(
            model_name='animematerials',
            name='studio',
        ),
    ]
