# Generated by Django 5.1.2 on 2024-11-02 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0023_studio_rename_nslug_index_name_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animematerials',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studio', to='anime.studio'),
        ),
    ]
