# Generated by Django 5.1.2 on 2024-11-02 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0024_animematerials_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animematerials',
            name='commentaries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='anime',
            field=models.ManyToManyField(blank=True, related_name='anime', to='anime.animematerials'),
        ),
        migrations.CreateModel(
            name='Commentaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('commentaries', models.TextField(max_length=10000)),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_id', to='anime.animematerials')),
            ],
        ),
    ]
