# Generated by Django 5.1.2 on 2024-11-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0025_alter_animematerials_commentaries_alter_index_anime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animematerials',
            name='commentaries',
        ),
    ]
