# Generated by Django 5.1.2 on 2024-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0029_alter_commentaries_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='animematerials',
            name='rating',
            field=models.TextField(choices=[('G', 'Подходит для всех возрастов.'), ('PG', 'Рекомендуется просмотр в присутствии родителей.'), ('PG-13', 'Рекомендуется для подростков 13 лет и старше.'), ('R', 'Подходит для лиц старше 17 лет.'), ('R+', 'Содержит легкую наготу или более откровенные сцены.')], default='G'),
        ),
    ]
